# Request
int32 control_type  # Control mode: 0 = Stop, 1 = Position Control, 2 = PWM Control
float64 kp          # Proportional control constant
float64 kd          # kd control constant
---
# Response
bool success        # Indicates if the control type was successfully set