std_msgs/Header header  # Standard message header
float32 motor_encoder   # Encoder value of the motor
float32 motor_velocity  # Motor velocity
float32 accel_x         # Acceleration in x-axis
float32 accel_y         # Acceleration in y-axis
float32 accel_z         # Acceleration in z-axis
float32 gyro_x          # Gyroscope reading in x-axis
float32 gyro_y          # Gyroscope reading in y-axis
float32 gyro_z          # Gyroscope reading in z-axis